vim.keymap.set('i', '(', '()<Esc>i')
vim.keymap.set('i', '[', '[]<Esc>i')
vim.keymap.set('i', '{<Enter>', '{<Enter>}<Esc>ko')
vim.keymap.set('i', '{{', '{}<Esc>i')
vim.keymap.set('i', "'", "''<Esc>i")
vim.keymap.set('i', '"', '""<Esc>i')
