[".config/kitty/themes/catppuccin-macchiato.conf"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/kitty/main/themes/macchiato.conf"
refreshPeriod = "168h"

[".config/alacritty/catppuccin-mocha.toml"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/alacritty/main/catppuccin-mocha.toml"
refreshPeriod = "168h"
