[".config/kitty/themes/catppuccin-macchiato.conf"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/kitty/main/themes/macchiato.conf"
refreshPeriod = "168h"

[".config/alacritty/catppuccin-mocha.toml"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/alacritty/main/catppuccin-mocha.toml"
refreshPeriod = "168h"

{{ if and (eq .chezmoi.os "linux") (eq .chezmoi.osRelease.id "arch") -}}
[".local/libexec/crispasr/crispasr"]
type = "archive-file"
url = "https://github.com/CrispStrobe/CrispASR/releases/download/v0.8.25/crispasr-linux-x86_64-vulkan.tar.gz"
path = "crispasr-linux-x86_64-vulkan/crispasr"
executable = true
checksum.sha256 = "d8bd2d0dbbf3bb721dd185f40b35974b47322bf010fde05d2052d6f04e48ef33"
checksum.size = 57934650

[".local/libexec/crispasr/libc2pa_c.so"]
type = "archive-file"
url = "https://github.com/CrispStrobe/CrispASR/releases/download/v0.8.25/crispasr-linux-x86_64-vulkan.tar.gz"
path = "crispasr-linux-x86_64-vulkan/libc2pa_c.so"
checksum.sha256 = "d8bd2d0dbbf3bb721dd185f40b35974b47322bf010fde05d2052d6f04e48ef33"
checksum.size = 57934650
{{ end -}}
