# Bopomofo Keyboard Layout
BopomofoKeyboardLayout=hsu
# Candidate List Layout
CandidateLayout=Vertical
# Selection Keys
SelectionKeys=asdfghjkl
# Selection Keys Count
SelectionKeysCount=9
# Space key chooses candidate
ChooseCandidateUsingSpace=False
# Show Candidate Phrase
SelectPhrase=before_cursor
# Move cursor after selection
MoveCursorAfterSelection=True
