vim.opt.autoindent = true
vim.opt.cursorline = true
vim.opt.ignorecase = true -- Case insensitive searching UNLESS /C or capital in search
vim.opt.incsearch = true
vim.opt.number = true
vim.opt.shell = 'zsh'
vim.opt.smarttab = true
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.expandtab = true
vim.opt.termguicolors = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 8
