alias gaa "git add --all"
alias gc "git commit -m"
alias gf "git fetch"
alias gl "git pull"
alias glg "git log"
alias gp "git push"
alias gst "git status"
alias la "ls -A"
alias lal "la -lh"
alias ll "ls -lh"
alias sdn "shutdown now"
alias tosync "cd ~/syncfolder/"
