abbr -a gaa "git add --all"
abbr -a gc "git commit -m"
abbr -a gf "git fetch"
abbr -a gl "git pull"
abbr -a glg "git log"
abbr -a gp "git push"
abbr -a gst "git status"
abbr -a sdn "shutdown now"
abbr -a tosync "cd ~/syncfolder/"
abbr -a ... "cd ../.."
abbr -a .... "cd ../../.."
abbr -a ..... "cd ../../../.."
abbr -a ...... "cd ../../../../.."
abbr -a ....... "cd ../../../../../.."
