
name: Test Dotfiles on Different OS

on:
  push:
    branches: ['*']
  pull_request:

concurrency:
  group: dotfiles-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-on-linux:
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        container: ["manjarolinux/base:latest", "archlinux:latest", "ubuntu:latest", "ubuntu:22.04"]
    container:
      image: ${{ matrix.container }}
      env:
        USER: dev
        HOME: /home/dev
        CHEZMOI_VERBOSE: 1
    steps:
      - name: Prepare environment
        run: |
          if command -v apt-get >/dev/null; then
            if [ "$(id -u)" = "0" ]; then
              apt-get update
              apt-get install -y sudo git curl
            else
              sudo apt-get update
              sudo apt-get install -y sudo git curl
            fi
            if ! command -v chezmoi >/dev/null; then
              sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
            fi
          elif command -v pacman >/dev/null; then
            if ! command -v sudo >/dev/null; then
              pacman -Syu --noconfirm sudo
            fi
            sudo pacman -Syu --noconfirm git chezmoi curl
          else
            exit 1
          fi

          sudo useradd -m dev || true
          echo "dev ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/dev
      - name: chezmoi init dotfiles
        run: |
          BRANCH=${{ github.head_ref || github.ref_name }}
          if command -v sudo >/dev/null; then
            sudo -u dev chezmoi init collieiscute --branch "$BRANCH" --apply -v
          else
            su dev -c "chezmoi init collieiscute --branch \"$BRANCH\" --apply -v"
          fi

  deploy-on-macos:
    name: macos:latest
    runs-on: macos-latest
    steps:
      - name: Prepare environment
        run: |
          if ! command -v chezmoi >/dev/null; then
            brew install chezmoi
          fi
          # Create a 'dev' user (macOS doesn't have useradd)
          # For demo, just set up an environment folder
          sudo mkdir -p /Users/dev
          sudo chown $USER /Users/dev
          echo "dev ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/dev
      - name: chezmoi init dotfiles
        run: |
          BRANCH=${{ github.head_ref || github.ref_name }}
          if command -v sudo >/dev/null; then
            sudo -u $USER chezmoi init collieiscute --branch "$BRANCH" --apply -v
          else
            chezmoi init collieiscute --branch "$BRANCH" --apply -v
          fi
