
name: Test Dotfiles on Different OS

on:
  push:
    branches: ['*']
  pull_request:

concurrency:
  group: dotfiles-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-on-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: ["manjarolinux/base:latest", "archlinux:latest", "ubuntu:latest", "ubuntu:22.04"]
    steps:
      - name: Run tests
        run: |
          echo "Running tests on ${{ matrix.container }}"

  deploy-on-macos:
    name: macos:latest
    runs-on: macos-latest
    steps:
      - name: Prepare environment
        run: |
          if ! command -v chezmoi >/dev/null; then
            brew install chezmoi
          fi
          # Create a 'dev' user (macOS doesn't have useradd)
          # For demo, just set up an environment folder
          sudo mkdir -p /Users/dev
          sudo chown $USER /Users/dev
          echo "dev ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/dev
      - name: chezmoi init dotfiles
        run: |
          if command -v sudo >/dev/null; then
            sudo -u $USER chezmoi init collieiscute --branch ${{ github.ref_name }} --apply -v
          else
            chezmoi init collieiscute --branch ${{ github.ref_name }} --apply -v
          fi
        shell: sh -e {0}
