[shell]
font_family = "JetBrainsMono Nerd Font"
telemetry_enabled = false
polkit_agent = true
clipboard_enabled = true
clipboard_history_max_entries = 100
clipboard_auto_paste = "auto"
screen_time_enabled = true

[shell.greeter_sync]
auto_sync = true

[shell.panel]
launcher_placement = "floating"
launcher_position = "center"
clipboard_placement = "floating"
clipboard_position = "center"
control_center_placement = "attached"
wallpaper_placement = "attached"
session_placement = "attached"

[shell.animation]
speed = 1.8

[shell.screen_corners]
enabled = true
size = 13

[shell.shadow]
direction = "center"

[shell.screenshot]
save_to_file = false
copy_to_clipboard = true
freeze_screen = false
pipe_to_command = false

[wallpaper]
enabled = true
fill_mode = "stretch"
directory = "~/.config/wallpapers"
transition_on_startup = false

[wallpaper.default]
path = "~/.config/wallpapers/xp_wallpaper.jpg"

[theme]
mode = "light"
source = "wallpaper"
wallpaper_scheme = "faithful"

[theme.templates]
enable_builtin_templates = true
enable_community_templates = true
builtin_ids = ["alacritty", "btop", "ghostty", "gtk3", "gtk4", "hyprland", "kitty", "qt", "wezterm"]
community_ids = ["opencode", "discord", "telegram", "neovim", "steam", "fastfetch", "zellij", "bat", "lazygit", "tmux"]

[notification]
enable_daemon = true
show_app_name = true
layer = "top"
background_opacity = 0.97

[osd]
position = "top_center"
orientation = "horizontal"
scale = 1.0
background_opacity = 0.14

[lockscreen]
enabled = true
blurred_desktop = false
blur_intensity = 0.5
tint_intensity = 0.3

[system.monitor]
enabled = true
cpu_temp_activity_threshold = 70
cpu_temp_critical_threshold = 100

[calendar]
enabled = true

[calendar.account.work]
name = "work"
type = "google"

[calendar.account.personal]
color = "primary"
name = "personal"
type = "google"

[weather]
enabled = true

[location]
address = "taipei"

[audio]
enable_overdrive = false
enable_sounds = false

[brightness]
enable_ddcutil = false

[idle]
pre_action_fade_seconds = 2.0

[idle.behavior.lock]
enabled = true
timeout = 300
action = "lock"

[idle.behavior.screen-off]
enabled = true
timeout = 600
action = "screen_off"

[keybinds]
validate = ["return", "kp_enter"]
cancel = ["escape"]
left = ["left"]
right = ["right"]
up = ["up"]
down = ["down"]

[plugins]
enabled = ["noctalia/screen_recorder", "noctalia/timer", "salemsayed/codexbar-meter", "tadomika_ari/w-engine"]
auto_update = "all"

[bar]
order = ["main"]

[bar.main]
enabled = true
position = "top"
auto_hide = false
reserve_space = true
layer = "top"
thickness = 33
background_opacity = 0.0
radius = 0
margin_ends = 0
margin_edge = 0
padding = 5
widget_spacing = 3
scale = 1.1
shadow = false
capsule = true
capsule_fill = "surface_variant"
capsule_opacity = 0.3
color = "primary"
icon_color = "primary"
start = ["tray", "w-engine", "codexbar-meter", "media"]
center = ["clock", "workspaces"]
end = ["volume", "group:net-status", "group:sys-status", "notifications", "clipboard", "session"]

[[bar.main.capsule_group]]
id = "net-status"
members = ["net-down", "net-up"]
fill = "surface_variant"
padding = 6.0
opacity = 0.3

[[bar.main.capsule_group]]
id = "sys-status"
members = ["cpu", "ram", "gpu", "vram", "temp", "battery"]
fill = "surface_variant"
padding = 3.0
opacity = 0.3

[widget.clock]
format = "{:%B %d %H:%M:%S}"
tooltip_format = "{:%A, %B %d, %Y}"

[widget.media]
hide_when_no_media = true
max_length = 320

[widget.codexbar-meter]
type = "salemsayed/codexbar-meter:bar"

[widget.w-engine]
type = "tadomika_ari/w-engine:w-engine-widget"

[widget.net-down]
type = "sysmon"
stat = "net_rx"
visualization = "none"
show_value = true

[widget.net-up]
type = "sysmon"
stat = "net_tx"
visualization = "none"
show_value = true

[widget.cpu]
type = "sysmon"
stat = "cpu_usage"
visualization = "graph"
show_value = false
show_glyph = false

[widget.gpu]
type = "sysmon"
stat = "gpu_usage"
visualization = "graph"
show_value = false
show_glyph = false

[widget.temp]
type = "sysmon"
stat = "cpu_temp"
visualization = "none"
show_value = true

[widget.ram]
type = "sysmon"
stat = "ram_pct"
visualization = "none"
show_value = true

[widget.vram]
type = "sysmon"
stat = "gpu_vram"
visualization = "none"
show_value = true

[widget.volume]
show_label = true

[widget.volume.actions]
scroll_down = "volume-down 3%"
scroll_up = "volume-up 3%"

[widget.battery]
show_label = true

[widget.notifications]
hide_when_no_unread = false

[widget.tray]
drawer = false

[dock]
enabled = true
active_monitor_only = true
auto_hide = true
background_opacity = 0.75
icon_size = 33
magnification_scale = 1.8
reserve_space = false
shadow = false
